version: "3.9"
services:
  function:
    build: ./function/
    extra_hosts:
    - "host.docker.internal:host-gateway"
    ports:
      - "9000:8080"
    deploy:
      resources:
        limits:
          memory: 128M
  baseline:
    build: ./baseline/
    ports:
      - "9000:8080"
  thumbnailer:
    build: ./thumbnailer/
    ports:
      - "9000:8080"    
    volumes:
      - ~/.aws:/root/.aws
